Use argocd to manage utilities for e2e-cluster
mattermost/mattermost-cloud pull request #1061
Opened 2024-07-11 19:01 UTC by andrleite

#### Summary
Use argocd to manage utilities for e2e-cluster

#### Ticket Link
 Fixes https://mattermost.atlassian.net/browse/CLD-7783

#### Release Note

```release-note
None
```

2024-07-12 00:14 UTC, gabrieljackson requested changes
I think we can make a few improvements which I outlined below

2024-07-12 00:14 UTC, gabrieljackson commented on e2e/tests/shared/shared.go
> +				},
We should use the constants for all these. Example:
```suggestion
				model.NginxCanonicalName: {
					Chart: model.UnmanagedUtilityVersion,
				},
```

2024-07-12 00:14 UTC, gabrieljackson commented on e2e/tests/shared/shared.go
> +func SetupTestWithDefaults(testName, utiliyManaged string) (*Test, error) {
I think passing in `utiliyManaged` as a bool makes a bit more sense than as a string.

```suggestion
func SetupTestWithDefaults(testName string, argoManagedUtilities bool) (*Test, error) {
```

2024-07-12 00:14 UTC, gabrieljackson commented on e2e/tests/shared/shared.go
> +			Provisioner:        config.Provisioner,
Instead of recreating the request we can just alter the existing one to change or add the values we want.

2024-07-12 14:13 UTC, nickmisasi reviewed
Nothing to add from Gabe's suggestions, just commenting so you can re-request review when you've addressed them!

2024-07-15 21:57 UTC, gabrieljackson approved these changes
LGTM. Thanks for addressing the feedback.

2024-07-16 00:18 UTC, merged