Draft: OIDC Authentication, and Cloud CLI Contexts
mattermost/mattermost-cloud pull request #1082
Opened 2024-10-09 19:07 UTC by nickmisasi

#### Summary
This PR introduces 2 major features

##### OIDC Authentication. 
Defaulted to off, unless the server is provided with a Client ID, Secret, and Organization URL. 
Setting the aforementioned parameters will result in the provisioner validating requests to /api/* contain a valid Access Token from Okta. 
Authentication for CLI's is handled using Device Authorization grants, via `cloud login` command. Authentication data (access tokens, refresh tokens, etc) are stored in a _context_

Screenshots:
Login page of Okta (Browser auto-opens)
![image](https://github.com/user-attachments/assets/1ce3d209-ae65-4f47-af4e-d5b2ad58a88d)
Logs in terminal when initiated:
![image](https://github.com/user-attachments/assets/b45f1c86-5c5c-4f3c-9181-bce85a2158f9)

##### CLI Contexts
Most users have their own custom hacks or bash scripts to automate the passing of `--server` to handle interacting with different environments. This PR introduces the concept of contexts, stored in `~/.cloud/contexts.json`

Contexts store:
- Server URL
- Auth Data (like your access and refresh tokens)
- An alias (for switching)
- Client ID, and Org URL to kick off authorization flow (if configured)

A new CLI option now exists `cloud contexts <command>` with the following options:
```
Manipulate local contexts for the Cloud CLI

Usage:
  cloud contexts [command]

Available Commands:
  create      Create a new context.
  delete      Delete a context.
  get         Get details of a specific context.
  list        List all contexts.
  set-current Set the current context.
  update      Update a context.
```
Additionally, a `cloud login` command has been added, which allows you to retrigger the login flow for a particular context, should you run into authentication issues. 
```
cloud login --help
Login to the Mattermost Cloud provisioning server.

Usage:
  cloud login [flags]

Flags:
      --context string   The name of the context to use.
  -h, --help             help for login
  ```

The `--server` parameter has been removed. Instead, use `cloud context create` to create a context for each Provisioner environment you interact with. To switch between them, use `cloud context set-current`. All `cloud` commands will initiate based off of the currently set context (todo: support `--context` to switch contexts for a single command)

On first run of the Cloud CLI with this change, the contexts.json file will be created for you, containing one context with alias `local` pointing at `http://localhost:8075`. 

When creating a new context, if you provide a Client ID and OrgURL, the CLI will automatically initiate the login flow for you. To skip the authentication flow, pass the argument `--skip-auth`

 

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-8406
#### Release Note

```release-note

```

2024-10-25 17:36 UTC, nickmisasi commented on internal/auth/device_authorization.go
> +	"golang.org/x/oauth2"
Borrowed the OAuth2 built in types for some marshaling, but couldn't use it for token exchange here as MS requires a custom scope to be passed, and this library doesn't support doing that when using refresh tokens

2024-11-12 13:15 UTC, esarafianou requested changes
First round of comments, but I'll re-review this.

2024-11-12 13:54 UTC, nickmisasi commented on cmd/cloud/main.go
> +	return cmd.Use == "migrate" || cmd.Use == "server" || cmd.Use == "login" || cmd.Parent().Use == "contexts"
It's the database migration command which is run directly against the database

2024-11-12 13:57 UTC, nickmisasi commented on cmd/cloud/server_flag.go
> +	command.Flags().StringSliceVar(&flags.RestrictedClientAllowedEndpointsList, "restricted-client-allowed-endpoints", []string{}, "The list of restricted endpoints.")
This is run through IaC YAML manifests anywhere that the authentication would matter - see [here](https://git.internal.mattermost.com/cloud-sre/kubernetes-workloads/gitops-platform/-/blob/main/apps/prod/manifests/cnc/provisioner/provisioner_deployment.yaml?ref_type=heads#L34) we currently set allow-list-cidr-ranges and vpn-cidr ranges similarly to the way these would be set here, so I expect we should be ok from the human error side

2024-11-12 13:57 UTC, nickmisasi commented on model/client.go
> +func NewClientWithOAuth(address string, headers map[string]string, clientID, clientSecret, tokenEndpoint string) *Client {
This is the client, which is consumed by calling packages like the CWS, Matterwick, Cloud Plugin, etc. This function will be used there

2024-11-14 14:08 UTC, nickmisasi commented on internal/auth/device_authorization.go
> +		case "access_denied":
Left over from Okta. Removed!

2024-11-14 14:08 UTC, nickmisasi commented on cmd/cloud/contexts.go
> +				contexts.CurrentContext = reflect.ValueOf(contexts.Contexts).MapKeys()[0].String()
I've adjusted this to only change the CurrentContext in the event that the CurrentContext is what was deleted

2024-11-14 14:12 UTC, nickmisasi commented on internal/auth/cli.go
> +	auth.AccessToken = newToken.AccessToken
I had left this intentionally as a "feature" to enforce re-authentications more frequently, but I guess we can defer that functionality to the auth side. I've changed it to match your suggestion but if you'd like me to change it back let me know.

2024-11-14 14:22 UTC, nickmisasi commented on internal/auth/device_authorization.go
> +		Scopes: []string{"openid", "profile", "offline_access", "api://provisioner/provisioner"},
`openid` scope is required when using OIDC. It's also what returns the `sub` field which is how we identify the user. If you don't pass it, you get an error `The provided value for the input parameter 'scope' is not valid. The scope profile offline_access is not valid. openid scope is required.`

2024-11-14 14:39 UTC, nickmisasi commented
Getting rate limited on a build step. Will try again later

2024-11-18 12:15 UTC, esarafianou commented on internal/auth/device_authorization.go
> +		Scopes: []string{"openid", "profile", "offline_access", "api://provisioner/provisioner"},
That's interesting, thanks for checking!

2024-11-18 12:41 UTC, esarafianou commented on internal/auth/cli.go
> +	auth.AccessToken = newToken.AccessToken
I see what you mean. Can we actually revert those changes? Apologies for that! 

Reasoning: 
1.  For public clients that are not single-page applications (SPAs), such as those utilizing the device authorization grant (device flow), the default refresh token lifetime is 90 days. This is already a lot for a public client but it's non-configurable. 
2. Each time a refresh token is used to acquire a new access token, Microsoft Entra ID issues a new refresh token, that inherits the same default lifetime as the original. As long as the refresh token is used within its valid period, it is continuously renewed, potentially allowing indefinite access without requiring the user to re-authenticate.

2024-11-19 11:46 UTC, esarafianou requested changes
2 last comments, looks great otherwise!

2024-11-19 11:46 UTC, esarafianou commented on model/client.go
> +	fmt.Println(c.oauthConfig)
This is printing the client secret. We should either print specific fields of the oauthConfig or remove this altogether.

2024-11-19 15:11 UTC, nickmisasi commented on internal/auth/cli.go
> +	auth.AccessToken = newToken.AccessToken
Reverted back to not using the new RefreshToken

2024-11-19 15:23 UTC, esarafianou approved these changes

2024-11-19 18:43 UTC, gabrieljackson requested changes
Heya, have some initial feedback from my testing.

2024-11-19 18:43 UTC, gabrieljackson commented on cmd/cloud/clicontext/clicontext.go
> +		WriteContexts(&contextsData)
We are ignoring the return error here and this seems to be hiding an issue where bootstrapping will fail on a completely new bootstrap. I believe the issue is the `.cloud` directory isn't being created.

2024-11-19 18:43 UTC, gabrieljackson commented on cmd/cloud/clicontext/clicontext.go
> +	contextFilePath := filepath.Join(homeDir, ".cloud", "contexts.json")
Let's take this logic and put it into a reusable helper function to rule out any typos on the default context file path.

2024-11-25 13:53 UTC, gabrieljackson approved these changes
Looks great! Let's get this merged so we can start testing it.

2024-11-26 16:04 UTC, merged