groups: add groups status endpoint
mattermost/mattermost-cloud pull request #370
Opened 2020-11-19 14:18 UTC by cpanato

#### Summary
The SRE team was discussing and find a need to have a way to get all groups status information in one shot, instead of doing a call per each group.
This will help to automate the dashboards as well

This PR adds the new endpoint that retrieves the status of all groups.

/cc @stafot @angeloskyratzakos 

#### Ticket Link
NONE

#### Release Note

```release-note
groups: add groups status endpoint
```

2020-11-19 14:18 UTC, cpanato commented
/kind feature

2020-11-19 14:28 UTC, angeloskyratzakos commented
You are the most amazing person ever! Thanks @cpanato for the addition!

2020-11-20 15:30 UTC, gabrieljackson requested changes

2020-11-20 16:03 UTC, cpanato commented on cmd/cloud/groups.go
> +	RunE: func(command *cobra.Command, args []string) error {
done, ptal

2020-11-20 16:47 UTC, gabrieljackson approved these changes
Thanks for cleaning up the CLI structure. Just a few thoughts, but looks good.

2020-11-20 16:47 UTC, gabrieljackson commented on internal/api/group.go
> +// returning the rollout status of the all groups.
nit:
```suggestion
// returning the rollout status of all groups.
```

2020-11-20 16:47 UTC, gabrieljackson commented on internal/api/group.go
> +		PerPage:        -1,
```suggestion
		PerPage:        model.AllPerPage,
```

2020-11-20 16:47 UTC, gabrieljackson commented on model/group_status.go
> +	ID     string
We could probably just add the `ID` to `GroupStatus` and then just use `[]GroupStatus` for the return type, but this works. Just an idea for later maybe.

2020-11-20 17:38 UTC, stylianosrigas approved these changes

2020-11-24 11:45 UTC, merged